language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
# command to install dependencies
install:
  - pip install . --use-mirrors
  - pip install argparse mock unittest2 --use-mirrors
# command to run tests
script: unittest2 discover tests
